# Generated by Django 5.2.5 on 2025-08-31 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('added', 'Item Added'), ('updated', 'Quantity Updated'), ('restocked', 'Restocked'), ('sold', 'Item Sold')], max_length=20)),
                ('old_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('change_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Change',
                'verbose_name_plural': 'Inventory Changes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
